routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('post');
});

Route::resource('post', 'PostController')->except(['create', 'edit']);

Route::resource('profile', 'ProfileController')->except(['index', 'create', 'store']);

Route::resource('comment', 'CommentController')->only(['store', 'update', 'destroy']);

Route::post('/comment/{comment}/create', 'CommentController@create')->name('comment.create');

Route::post('/post/{post}', 'PostController@like')->name('post.like');

Route::post('/comment/{comment}', 'CommentController@like')->name('comment.like');

Route::post('/profile/{profile}', 'ProfileController@follow')->name('profile.follow');

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $table = "posts";
	protected $guarded = [];

	public function user()
	{
		return $this->belongsTo('App\User', 'user_id');
	}

	public function comments()
	{
		return $this->hasMany('App\Comment', 'post_id');
	}

	public function like_posts()
	{
		return $this->belongsToMany('App\User', 'like_posts', 'post_id', 'user_id');
	}
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;
use App\Post;
use App\LikePost;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'desc')->get();

        return view('post.index', compact('posts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'post' => 'required',
        ]);

        $user = Auth::user();
        $post = $user->posts()->create([
            'text' => $request['post'],
        ]);

        Alert::success('Success', 'Upload Post Successful');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('post.detail', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'post' => 'required',
        ]);

        $post = Post::find($id);
        $post->text = $request['post'];
        $post->save();

        Alert::success('Success', 'Update Post Successful');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();

        Alert::success('Success', 'Delete Post Successful');
        return back();
    }

    public function like($id)
    {
        $post = Post::find($id);
        $like_post_status = LikePost::where('post_id', $id)->where('user_id', Auth::id())->first();

        if ($like_post_status) {
            $post->like_posts()->detach(Auth::id());
        } else {
            $post->like_posts()->attach(Auth::id());
        }
        return back();
    }
}

resources/views/post/detail.blade.php
@extends('podcast.master')

@push('scripts-head')
<style>
	div .post-item img {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 650px;
	}
</style>
@endpush

@section('content')
<div class="p-2 py-5" style="margin-left: 150px; margin-right: 150px">
	<div class="border px-4 py-3">
		<div class="row py-3">
			<div class="col-1 px-1">
				<img src="{{asset($post->user->profile->photo)}}" width="100" height="100" style="object-fit: cover" class="rounded-circle mx-auto">
			</div>

			<div class="col-11 px-3 mx-auto text-justify">
				<a href="{{ route('profile.show', ['profile' => $post->user->id]) }}">
					<h5>{{ $post->user->name }}</h5>
				</a>
				<div class="post-item">
					{!! $post->text !!}
				</div>

				<div class="row mb-4 justify-content-md-center">
					<div class="col-2">
						<form action="{{ route('post.like', ['post' => $post->id]) }}" method="POST">
							@csrf
							@if ($post->like_posts()->where('post_id', $post->id)->where('user_id', Auth::id())->get()->count())
							<button type="submit" class="btn btn-outline-primary btn-block bg-transparent" role="button">
								<img src="{{ asset('podcast/images/favorite-heart-button.png') }}" width="20">
								<b class="ml-1">{{ $post->like_posts()->where('post_id', $post->id)->get()->count() }}</b>
							</button>
							@else
							<button type="submit" class="btn btn-outline-primary btn-block bg-transparent" role="button">
								<img src="{{ asset('podcast/images/favorite-heart-outline-button.png') }}" width="20">
								<b class="ml-1">{{ $post->like_posts()->where('post_id', $post->id)->get()->count() }}</b>
							</button>
							@endif
						</form>
					</div>
				</div>

				<form action="{{ route('comment.create', ['comment' => $post->id]) }}" method="POST">
					@csrf
					<div class="row mb-4">
						<div class="col-11">
							<textarea class="form-control" id="comment" name="comment" value="{{ old('comment','') }}" rows="3" placeholder="your comment here"></textarea>
						</div>
						<div class="col-1">
							<button class="btn bg-white" role="button"><img src="{{ asset('podcast/images/send-button.png') }}" width="40"></button>
						</div>
					</div>
				</form>

				@foreach ($post->comments as $comment)
				<div class="row">
					<div class="col justify-content-around">
						<div class="d-flex">
							<a href="{{ route('profile.show', ['profile' => $comment->user->id]) }}">
								<h5>{{ $comment->user->name }}</h5>
							</a>
							@if (Auth::id() == $comment->user->id || Auth::id() == $post->user->id)
							<button class="btn btn-secondary dropdown-toggle ml-2" style="height: 30px; padding: 5px;" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Option
							</button>

							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								@if (Auth::id() == $comment->user->id)
								<button type="button" class="dropdown-item" data-toggle="modal" data-target="#Comment{{$post->id}}Modal{{$comment->id}}">
									Edit
								</button>
								@endif
								<form action="{{ route('comment.destroy', ['comment' => $comment->id]) }}" method="post">
									@csrf
									@method('DELETE')
									<input type="submit" value="Delete" class="dropdown-item">
								</form>
							</div>
							@endif
						</div>

						<div class="d-flex">
							<p>{!! nl2br($comment->text) !!}</p>

							<div>
								<form action="{{ route('comment.like', ['comment' => $comment->id]) }}" method="POST">
									@csrf
									@if ($comment->like_comments()->where('comment_id', $comment->id)->where('user_id', Auth::id())->get()->count())
									<button class="btn ml-2 p-1 bg-transparent" type="submit" style="height: 30px; padding: 5px;" role="button">
										<img src="{{ asset('podcast/images/favorite-heart-button.png') }}" width="20">
										<b class="ml-1">{{ $comment->like_comments()->where('comment_id', $comment->id)->get()->count() }}</b>
									</button>
									@else
									<button class="btn ml-2 p-1 bg-transparent" type="submit" style="height: 30px; padding: 5px;" role="button">
										<img src="{{ asset('podcast/images/favorite-heart-outline-button.png') }}" width="20">
										<b class="ml-1">{{ $comment->like_comments()->where('comment_id', $comment->id)->get()->count() }}</b>
									</button>
									@endif
								</form>
							</div>

						</div>
					</div>
				</div>
				@endforeach
				<label class="text-muted font-italic m-0"><small>{{ count($post->comments) }} comments</small></label>
			</div>
		</div>
		<hr>
	</div>
</div>

<!-- Edit Comment Modal -->
@foreach ($post->comments as $comment)
<div class="modal fade bd-example-modal-lg" id="Comment{{$post->id}}Modal{{$comment->id}}" tabindex="-1" role="dialog" aria-labelledby="Comment{{$post->id}}Modal{{$comment->id}}Title" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="Comment{{$post->id}}Modal{{$comment->id}}Title">Edit Your Comment</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{{ route('comment.update', ['comment' => $comment->id])}}" method="POST">
					@csrf
					@method('PUT')
					<div class="form-group">
						<textarea class="form-control" id="comment" name="comment" rows="3">{{ $comment->text }}</textarea>
					</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Save changes</button>
				</form>
			</div>
		</div>
	</div>
</div>
@endforeach

@endsection

resources/views/post/index.blade.php
@extends('podcast.master')

@push('scripts-head')
<style>
	div .post-item img {
		display: block;
		margin-left: auto;
		margin-right: auto;
		width: 650px;
	}
</style>
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush

@section('content')
<div class="p-2 py-5" style="margin-left: 150px; margin-right: 150px">
	<div class="row mb-5">
		<div class="col-1 px-1">
			<img src="{{asset(Auth::user()->profile->photo)}}" width="100" height="100" style="object-fit: cover" class="rounded-circle mx-auto">
		</div>

		<div class="col-11">
			<form action="{{ route('post.store') }}" method="POST">
				@csrf
				<div class="form-group">
					<h5 class="text-center">Create your post here</h5>
					<textarea name="post" class="form-control my-editor">{!! old('post', '') !!}</textarea>
				</div>

				<input type="submit" class="btn btn-info btn-lg btn-block" role="button" value="Create Post">
			</form>
		</div>
	</div>

	<div class="border px-4 py-3">
		@forelse ($posts as $post)
		<div class="row py-3">
			<div class="col-1 px-1">
				<img src="{{asset($post->user->profile->photo)}}" width="100" height="100" style="object-fit: cover" class="rounded-circle mx-auto">
			</div>

			<div class="col-11 px-3 mx-auto text-justify">
				<a href="{{ route('profile.show', ['profile' => $post->user->id]) }}">
					<h5>{{ $post->user->name }}</h5>
				</a>
				<div class="post-item">
					{!! $post->text !!}
				</div>

				<div class="row mb-4">
					<div class="col-2">
						<form action="{{ route('post.like', ['post' => $post->id]) }}" method="POST">
							@csrf
							@if ($post->like_posts()->where('post_id', $post->id)->where('user_id', Auth::id())->get()->count())
							<button type="submit" class="btn btn-outline-primary btn-block bg-transparent" role="button">
								<img src="{{ asset('podcast/images/favorite-heart-button.png') }}" width="20">
								<b class="ml-1">{{ $post->like_posts()->where('post_id', $post->id)->get()->count() }}</b>
							</button>
							@else
							<button type="submit" class="btn btn-outline-primary btn-block bg-transparent" role="button">
								<img src="{{ asset('podcast/images/favorite-heart-outline-button.png') }}" width="20">
								<b class="ml-1">{{ $post->like_posts()->where('post_id', $post->id)->get()->count() }}</b>
							</button>
							@endif
						</form>
					</div>
					<div class="col-10">
						<a class="btn btn-info btn-sm btn-block" href="{{ route('post.show', ['post' => $post->id]) }}" role="button">View more comments</a>
					</div>
				</div>

				<form action="{{ route('comment.create', ['comment' => $post->id]) }}" method="POST">
					@csrf
					<div class="row mb-4">
						<div class="col-11">
							<textarea class="form-control" id="comment" name="comment" value="{{ old('comment','') }}" rows="3" placeholder="your comment here"></textarea>
						</div>
						<div class="col-1">
							<button class="btn bg-white" role="button"><img src="{{ asset('podcast/images/send-button.png') }}" width="40"></button>
						</div>
					</div>
				</form>

				@if(count($post->comments))
				<div class="row">
					<div class="col justify-content-around">
						<div class="d-flex">
							<a href="{{ route('profile.show', ['profile' => $post->comments[0]->user->id]) }}">
								<h5>{{ $post->comments[0]->user->name }}</h5>
							</a>
							@if (Auth::id() == $post->comments[0]->user->id || Auth::id() == $post->user->id)
							<button class="btn btn-secondary dropdown-toggle ml-2" style="height: 30px; padding: 5px;" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Option
							</button>

							<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								@if (Auth::id() == $post->comments[0]->user->id)
								<button type="button" class="dropdown-item" data-toggle="modal" data-target="#Comment{{$post->id}}Modal{{$post->comments[0]->id}}">
									Edit
								</button>
								@endif
								<form action="{{ route('comment.destroy', ['comment' => $post->comments[0]->id]) }}" method="post">
									@csrf
									@method('DELETE')
									<input type="submit" value="Delete" class="dropdown-item">
								</form>
							</div>
							@endif
						</div>

						<div class="d-flex">
							<p>{!! nl2br($post->comments[0]->text) !!}</p>

							<div>
								<form action="{{ route('comment.like', ['comment' => $post->comments[0]->id]) }}" method="POST">
									@csrf
									@if ($post->comments[0]->like_comments()->where('comment_id', $post->comments[0]->id)->where('user_id', Auth::id())->get()->count())
									<button class="btn ml-2 p-1 bg-transparent" type="submit" style="height: 30px; padding: 5px;" role="button">
										<img src="{{ asset('podcast/images/favorite-heart-button.png') }}" width="20">
										<b class="ml-1">{{ $post->comments[0]->like_comments()->where('comment_id', $post->comments[0]->id)->get()->count() }}</b>
									</button>
									@else
									<button class="btn ml-2 p-1 bg-transparent" type="submit" style="height: 30px; padding: 5px;" role="button">
										<img src="{{ asset('podcast/images/favorite-heart-outline-button.png') }}" width="20">
										<b class="ml-1">{{ $post->comments[0]->like_comments()->where('comment_id', $post->comments[0]->id)->get()->count() }}</b>
									</button>
									@endif
								</form>
							</div>
						</div>
					</div>
				</div>
				@endif
				<label class="text-muted font-italic m-0"><small>{{ count($post->comments) }} comments</small></label>
			</div>
		</div>
		<hr>
		@empty
		<h4 class="text-center">Empty</h4>
		@endforelse
	</div>
</div>

<!-- Edit Comment Modal -->
@foreach ($posts as $post)
@if (count($post->comments))
<div class="modal fade bd-example-modal-lg" id="Comment{{$post->id}}Modal{{$post->comments[0]->id}}" tabindex="-1" role="dialog" aria-labelledby="Comment{{$post->id}}Modal{{$post->comments[0]->id}}Title" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="Comment{{$post->id}}Modal{{$post->comments[0]->id}}Title">Edit Your Comment</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{{ route('comment.update', ['comment' => $post->comments[0]->id])}}" method="POST">
					@csrf
					@method('PUT')
					<div class="form-group">
						<textarea class="form-control" id="comment" name="comment" rows="3">{{ $post->comments[0]->text }}</textarea>
					</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Save changes</button>
				</form>
			</div>
		</div>
	</div>
</div>
@endif
@endforeach

@endsection

@push('scripts')
<script>
	var editor_config = {
		path_absolute: "/",
		selector: "textarea.my-editor",
		plugins: [
			"advlist autolink lists link image charmap print preview hr anchor pagebreak",
			"searchreplace wordcount visualblocks visualchars code fullscreen",
			"insertdatetime media nonbreaking save table contextmenu directionality",
			"emoticons template paste textcolor colorpicker textpattern"
		],
		toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
		relative_urls: false,
		file_browser_callback: function(field_name, url, type, win) {
			var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
			var y = window.innerHeight || document.documentElement.clientHeight || document.getElementsByTagName('body')[0].clientHeight;

			var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
			if (type == 'image') {
				cmsURL = cmsURL + "&type=Images";
			} else {
				cmsURL = cmsURL + "&type=Files";
			}

			tinyMCE.activeEditor.windowManager.open({
				file: cmsURL,
				title: 'Filemanager',
				width: x * 0.8,
				height: y * 0.8,
				resizable: "yes",
				close_previous: "no"
			});
		}
	};

	tinymce.init(editor_config);
</script>
@endpush